### ISSUE TITLE
"Noteworthy" is a very ambigious word.

### ISSUE THREAD

**Issue by johannesgunnar** [GooseNinja/Icelandic-GameDev#4]
"Noteworthy games from Icelandic developers". The wording of this makes it slightly tricky for me to decide if I should add game or not. Who decides what is noteworthy and what is not? Are ALL finished games allowed? or only games that have reached a certain level of popularity? Only commercial games?

**Comment by GooseNinja** [comment]
Good question. 
Everyone can take part in deciding what games should or should not be added to the list. 
If someone adds a pull request (Or submits an issue) with games to add, everyone can comment on it. 

At this time, the only games I'm not eager to put on the list are GameJam games and simple prototypes. But I'm flexible on the subject. 

And I'll admit that I'm not the best at wording things, and everything up to this point has been without giving it too much thought. So any suggestions on wording are appreciated!

**Comment by GooseNinja** [comment]
I don't look at this as "My list". It belongs to everyone that want's to own it. So I'd love for everyone to participate in setting the rules for how we should shape it.

**Comment by alexandrabjarg** [comment]
I agree that "noteworthy" is maybe not the best choice of wording, but I also agree with @GooseNinja on that it shouldn't include gamejam games, prototypes, etc. That way the list will just become a monster. However, I do feel that "small games" should also belong on the list? Such as [Volodka](http://volodka.com/) by Torfi, Marco and Jói or [Prismatica](http://store.steampowered.com/app/377500/) by Loomus (Þórður Matthíasson). I think we should probably agree on some sort of definition of the type of game that goes on the list, and then maybe a different title for the list if needed. 

If we agree that those types of games belong on the list, I can submit issues for those two examples.

**Comment by GooseNinja** [comment]
Yeah, I think those two games should be on the list @alexandrabjarg :D

**Comment by alexandrabjarg** [comment]
Thinking about the definition of "noteworthy* games", I would go for something like: "Finished games that are available somewhere to buy/download/play, excluding game jam games". This automatically excludes prototypes but doesn't prevent non-commercial games from being on the list.

*Until we find a better word for it.

**Comment by GooseNinja** [comment]
That's a good suggestion. I will change it to that. Until or if we find something better :)
